version: 2.0
defaults: &defaults
  working_directory: ~/ride_my_way_lagos
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
      environment:
        RAILS_ENV: test
        PGHOST: 127.0.0.1
        DATABASE_URL: "postgres://ubuntu@localhost:5432/circle_test"
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: circle_test
        POSTGRES_PASSWORD: ""
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  backend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/ride_my_way_lagos/tmp
      - run: 
          name: Setup dependencies
          command: |
            bundle install --without production --path=${BUNDLE_PATH:-vendor/bundle}
            bundle exec rake db:create db:migrate
      - run: 
          name: Run backend tests
          command: |
            bundle exec rspec
            ./tmp/cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.backend.json coverage/backend/.resultset.json
      - persist_to_workspace:
          root: tmp
          paths: 
            - codeclimate.backend.json

  upload-coverage:
    <<: *defaults
    environment: 
      - CC_TEST_REPORTER_ID: 17f0492c7c78661601389189f29e6e66d6ce01e9fa37fa7828759d9bdb6ba7d2
    steps:
      - attach_workspace:
          at: ~/ride_my_way_lagos/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2

  commit:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - upload-coverage:
          requires:
             - backend-tests