# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  # adapter: sqlite3
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  host: localhost

development:
  # <<: *default
  # database: db/development.sqlite3
  <<: *default
  DATABASE_URL: postgresql://postgres:@127.0.0.1:5432/ride_my_way_dev

test:
  # <<: *default
  # database: db/test.sqlite3
  <<: *default
  DATABASE_URL: postgresql://postgres:@127.0.0.1:5432/ride_my_way_test

production:
  # <<: *default
  # database: db/production.sqlite3
  <<: *default
  DATABASE_URL: postgresql://postgres:@127.0.0.1:5432/ride_my_way_live
